Repository dusk-network/dusk-blindbid, pull requests merged in 2020-08, with the labels that each got.

#33 Add ECC-gate dependant constraints to the blindbid gadgets
  Cargo.toml
  src/bid.rs
  src/bid/encoding.rs
  src/proof.rs
  src/score_gen/score.rs
Labels: area:cryptography, type:feature

#35 Encryption impl with ElGamal
  Cargo.toml
  src/bid/bid.rs
  src/bid/encoding.rs
  src/bid/errors.rs
  src/bid/mod.rs
  src/proof.rs
  src/score_gen/score.rs
Labels: area:cryptography, type:refactor

#40 Replace failiure with `Anyhow` & `thiserror`
  Cargo.toml
  src/bid/bid.rs
  src/bid/encoding.rs
  src/bid/errors.rs
  src/lib.rs
  src/proof.rs
  src/score_gen/errors.rs
  src/score_gen/score.rs
Labels: type:refactor

#41 Remove ctant witness inclusions for Pedersen Comm
  src/proof.rs
Labels: area:cryptography, type:refactor

#44 Refactor documentation upload script
  .travis.yml
Labels: area:testing

#45 Import GENERATORS in extended coordinates directly
  src/bid/encoding.rs
  src/proof.rs
  src/score_gen/score.rs
Labels: type:refactor

#49 Port gadgets from `plonk_gadgets` repo and remove the ones defined here.
  Cargo.toml
  src/proof.rs
  src/score_gen.rs
  src/score_gen/mod.rs
  src/score_gen/score.rs
Labels: area:cryptography, type:refactor, type:tech-debt

#53 Fix plonk_gadgets dependency in Cargo.toml
  Cargo.toml
Labels: type:bug, type:tech-debt

#47 Implements #46 - Poseidon cipher to encrypt value
  Cargo.toml
  src/bid/bid.rs
  src/bid/encoding.rs
  src/bid/errors.rs
  src/lib.rs
  src/proof.rs
  src/score_gen/score.rs
Labels: area:cryptography, type:refactor

#57 Add copyright + licensing headers
  Cargo.toml
  src/bid/bid.rs
  src/bid/encoding.rs
  src/bid/errors.rs
  src/bid/mod.rs
  src/lib.rs
  src/proof.rs
  src/score_gen/errors.rs
  src/score_gen/mod.rs
  src/score_gen/score.rs
Labels: documentation
