Repository dusk-network/dusk-blindbid, pull requests merged in 2020-09, with the labels that each got.

#59 Single Bid approach
  src/bid/bid.rs
  src/bid/encoding.rs
  src/bid/mod.rs
  src/proof.rs
  src/score_gen/mod.rs
  src/score_gen/score.rs
  tests/bid_tests.rs
Labels: area:block-generation, area:cryptography, type:refactor

#61 Pki integration & Bid fields refactor
  Cargo.toml
  src/bid/bid.rs
  src/bid/encoding.rs
  src/lib.rs
  src/proof.rs
  src/score_gen/errors.rs
  src/score_gen/score.rs
  tests/bid_tests.rs
Labels: area:block-generation, area:cryptography, type:feature, type:refactor

#62 Implement Kelvin + Read/Write =To/From bytes traits & fns
  Cargo.toml
  src/bid/bid.rs
  src/bid/encoding.rs
  src/bid/errors.rs
  src/proof.rs
  tests/bid_tests.rs
Labels: area:block-generation, type:feature

#64 Make PoseidonTree<Bid, Blake2b> possible
  Cargo.toml
  src/bid/bid.rs
  src/bid/encoding.rs
  src/proof.rs
  tests/bid_tests.rs
Labels: area:conf&build, area:cryptography, status:blocker, type:feature

#70 Circuit trait impl for BlindBid circuit
  Cargo.toml
  src/lib.rs
  src/proof.rs
  tests/bid_tests.rs
Labels: area:cryptography, type:refactor

#71 Normalize crate name using dusk-blindbid
  Cargo.toml
  tests/bid_tests.rs
Labels: area:block-generation, type:refactor

#73 Migrate CI to Github Actions, fix license headers
  .github/workflows/dusk_ci.yml
  .travis.yml
  src/bid/bid.rs
  src/bid/encoding.rs
  src/bid/errors.rs
  src/bid/mod.rs
  src/lib.rs
  src/proof.rs
  src/score_gen/errors.rs
  src/score_gen/mod.rs
  src/score_gen/score.rs
  tests/bid_tests.rs
Labels: area:conf&build, area:documentation
